project:
  type: website
  output-dir: docs

website:
 sidebar:
    style: "docked"
    search: true
    logo: profile.png
    type: "light"
    background: "primary"
    foreground: "light"
    collapse-level: 2 
    contents:
      - section: "Title page"
        contents:
          - index.qmd
      - section: "Abstract"    
        contents: 
          - abstract.qmd
      - section: "Introduction"    
        contents: 
          - introduction.qmd    
      - section: "Literature Review"
        contents:
          - review.qmd
      - section: "Methodology"
        contents:
          - section: "Data Sources and Collection"
            contents:
              - Turf_Fields_Data.qmd
              - Landsat8.qmd
              - Stations_Data.qmd
              - Stations_Data_Spatial_Join.qmd
              - Weather_Data.qmd
          - section: "Data Cleaning and Preprocessing"
            contents:
              - Data_Integration_and_Selection.qmd
              - Data_Cleaning.qmd
      - section: "Results"
        contents:
          - section: "Visualizing Data, Investigating Correlations, and Applying Regression Analysis"  # Subsection 1
            contents: 
              - Data_Visualisation.qmd
              - Correlations.qmd
              - Regression.qmd
              - Assumptions.qmd
          - section: "Machine Learning Regression"
            contents: 
              - Machine_Learning.qmd
              - Machine_Learning_Plots.qmd
          - section: "Time Series Forecasting"
            contents: 
              - Prophet.qmd
      - section: "Discussion" 
        contents:
          - discussion.qmd 
      - section: "Conclusions"  
        contents:
          - conclusions.qmd 
      - section: "References"  
        contents:
          - references.qmd    

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
