project:
  type: website
  output-dir: docs

website:
 sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Main Page"
        contents:
          - index.qmd
      - section: "Data Sources and Collection"
        contents:
          - Turf_Fields_Data.qmd
          - Stations_Data.qmd

          
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

