project:
  type: website
  output-dir: docs

website:
 sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Main Page"
        contents:
          - index.qmd
      - section: "Data Sources and Collection"
        contents:
          - Turf_Fields_Data.qmd
          - Landsat8.qmd
          - Stations_Data.qmd
          - Stations_Data_Spatial_Join.qmd
      - section: "Data Cleaning and Preprocessing"
      - section: "Data Integration and Joins"
      - section: "Data Integration and Joins"
      - section: "Statistical Methods"

      
      



          

          
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

