project:
  type: website
  output-dir: docs

website:
 sidebar:
    style: "docked"
    search: true
    logo: profile.png
    type: "light"
    background: "primary"
    foreground: "light"
    collapse-level: 2 
    contents:
      - section: "Main Page"
        contents:
          - index.qmd
      - section: "Data Sources and Collection"
        contents:
          - Turf_Fields_Data.qmd
          - Landsat8.qmd
          - Stations_Data.qmd
          - Stations_Data_Spatial_Join.qmd
          - Weather_Data.qmd
      - section: "Time Series Analysis"
      - section: "Data Cleaning and Preprocessing"
        contents:
          - Data_Integration_and_Selection.qmd
          - Data_Cleaning.qmd
          - Data_Visualization.qmd
      - section: "Data Integration and Joins"
      
      - section: "Data Integration and Joins"
      - section: "Statistical Methods"

          
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

