---
title: "Conclusions"
---



To conclude, the seminar research delved into the relationship between the Land Surface Temperature of synthetic turf fields and climate factors during New York's summer months. This research aimed to comprehend the effect of climate variables on the Land Surface Temperature of synthetic turf fields. This is due to the popularity of synthetic turf fields and the concerns about rising temperatures of astroturf that could cause health and environmental issues.
The seminar research found low to moderate correlations between climate factors and Land Surface Temperature. A linear model using climate factors was found to have a moderate explanation of variance.  The Random Forest model enhanced predictive accuracy using climate factors and improved the explanation of variance, but not above a moderate level. Future research should explore the role of additional climate factors, such as humidity and wind speed. Additionally, more advanced machine learning methods techniques may offer enhanced predictive accuracy. Also, expanding the research area outside New York could lead to improved conclusions due to the diversity of climate patterns. In addition, the seminar presented research on predicting astroturf temperature dynamics using the Prophet Forecasting Procedure by Facebook. The model predicts an increase in land surface temperature (LST) during summer months over the next decade. This rise could lead to increased environmental damage and health problems related to astroturf.
Introduction:
Synthetic turf fields have become popular for sports and recreational activities worldwide due to their ease of installation and low maintenance requirements. However, it is crucial to consider the impact of Land Surface Temperature on human health and the environment. Elevated Land Surface Temperature of synthetic turf fields can have a variety of consequences, ranging from discomfort to heat-related health issues and environmental impacts. To address these concerns, it is essential to understand the complex relationship between climate factors and LST on synthetic turf fields.
The research question of this seminar is:
What is the effect of climate factors on the Land Surface Temperature of synthetic turf fields during the summer months?
This seminar research hypothesizes that climate factors will have a significant effect on the Land Surface Temperature of synthetic turf fields during the summer months, and the significant climate factors can be used to build a prediction model of future Land Surface Temperature of synthetic turf fields during the summer months.

