---
title: "Discussion"
---

This seminar research examined the relationship between Land Surface Temperature (LST) and several climate factors, such as Average Temperature, Minimum Temperature, Maximum Temperature, and Precipitation on synthetic turf fields in the New York area during the summer months of June, July, and August. The results of the correlation tests showed a significant and positive correlation between LST and temperature factors, except for precipitation. This suggests that the amount of precipitation was likely not significant enough to affect LST. The LST values were extracted from code free of clouds and their shadows, which could not have caused a decrease in LST. Therefore, it is reasonable to understand that there will be no significant correlation between precipitation and LST. 

It is worth noting that the other correlation tests performed support the initial hypothesis that higher temperatures would coincide with elevated LST values. However, it should be emphasized that the level of correlation observed was only low to medium, which indicates only partial support for the hypothesis. With the results of the correlation tests, a linear model was developed to explain the variations in LST through temperature variables, and the results showed that approximately 40.6% of the variance in LST could be explained by the average and minimum temperatures. The average temperature contributes positively, and the minimum temperature contributes a negative effect. However, it is interesting to note that the maximum mean temperature was insignificant in the linear regression. A reasonable hypothesis from the literature review is that the synthetic fields receive a lot of irrigation, which prevents them from heating up beyond what is desired. On the hotter days of the summer months, continuous and intensive irrigation may lower the temperature of the synthetic fields to lower values and, by that, interrupt a possible linear relationship between LST and maximum mean temperature. 

The Linear regression model accuracy is limited due to the multi-correlation of predictive variables and lack of homoscedasticity. To address this, a machine learning model was used to enhance predictive accuracy. The Random Forest machine learning model was found to be a useful model, surpassing the linear regression model with a mean R-squared value of 0.47. This improvement indicates that the Random Forest model can explain 7% more variance in LST, providing a more accurate prediction. However, it is important to note that the Random Forest model has performed poorly in predicting extremely low or high LST values. It should be taken into consideration when predicting LST in colder and warmer periods during the summer months.

In order to improve the analysis of the LST values of the synthetic turf fields in New York, a forward-looking methodology was employed. The Prophet forecasting procedure was used for predicting future LST values for the summer months of the next decade (2023-2033). The Prophet forecasting procedure is capable of dealing with time series data that exhibit seasonality and is also able to handle flexible and versatile types of data, making it a convenient tool to utilize and configure for prediction. The Prophet model predicts that LST values will increase during the summer months in the next decade. The predictions show a wide range of temperature scenarios, with the lowest estimated temperature being 37.34 degrees Celsius and the highest being 50.35 degrees Celsius. The model provides a confidence interval that indicates the possibility of LST exceeding the 50 to 70 degrees Celsius range over the next decade. While it is likely that the LST will not exceed 70 degrees due to intensive irrigation, as it is commonly practiced today, the synthetic fields will still experience an increase in temperature, according to the forecast. This will increase water and energy consumption to keep the synthetic grass fields cool, which could cause environmental damage. In addition to all these results, it is important to note that the data was collected from weather stations near the synthetic fields and at a certain distance that could affect the results. It is also likely to assume that various gases affect temperature near the airports where the weather stations are located. 

The data visualization found that Land Surface Temperature data exhibits temperature patterns yearly and monthly. These patterns show cooler and warmer years, with specific months, such as July, having the highest temperatures. This wide range of values could indicate that certain fields may have been under-maintained or lacked proper irrigation systems during some years in the research, which could explain the variability in temperature values.

Finally, according to the hypothesis, the seminar research created two moderate prediction models of the future Land Surface Temperature of synthetic turf fields during the summer months using significant climate factors.
