---
title: "Literature Review"
---

This literature review explores the relationship between astroturf, temperature increases, health impacts, and climate implications. Specifically, the literature review explores the high temperatures that astroturf can reach, how high temperatures of astroturf may affect the health of athletes and other users and potential climate implications.

Astroturf was initially praised for its resilience and year-round playability (Kanaan et al., 2020). However, with time, it has raised growing concerns regarding its impact on local temperatures, climate patterns, and health outcomes (Russo et al., 2022; Gould et al., 2022). As the adoption of astroturf in various recreational settings continues to grow, it becomes imperative to understand its implications for temperature dynamics, public health, and climate change (Russo et al., 2022).

Astroturf has become increasingly popular as an alternative to natural grass in sports facilities. In 2020, approximately 24.6 million square meters of astroturf were installed in North America, according to the Synthetic Turf Council (Russo et al., 2022). Astroturf was initially designed to offer a low-maintenance and cost-effective solution for high schools, colleges, and professional stadiums (Jastifer et al., 2018). Its popularity has grown due to the development of new synthetic surfaces, such as infill systems that provide playing quality similar to natural turfgrass. These infill systems, like sand and granulated rubber, have attracted users seeking better performance and safety characteristics (Jastifer et al., 2018).

However, the increased adoption of astroturf has raised concerns about its environmental impact and athlete well-being (Gould et al., 2022). Despite the advantages of astroturf, such as low maintenance and minimal irrigation requirements, these benefits are only partly valid (Kanaan et al., 2020). If installed incorrectly, astroturf can result in insufficient drainage and a planarity variation (Jastifer et al., 2018).

It has been reported that there are significant temperature differences between astroturf and natural turfgrass surfaces. Under similar conditions, astroturf has been found to be 35-60°C hotter than natural turfgrass (McNitt et al., 2007). This temperature difference is mainly attributed to the properties of the synthetic fibers used in astroturf, which are made of extruded polyethylene and dyed green. These fibers have a high rate of solar radiation absorption and minimal light reflectance, which causes the surface temperature to rise as high as 93°C on hot, sunny days (Thoms et al., 2014; McNitt et al., 2007). Moreover, astroturf’s hydrophobic and compact nature worsens heat retention, making it resistant to cooling by wind or water. As a result, it requires a significant amount of irrigation, meaning it must be watered every few hours on sunny days for about 20 minutes (Kanaan et al., 2020).

The heat generated on Astroturf fields has direct and diverse consequences on human health. Prolonged exposure to elevated temperatures significantly increases the risk of heat-related illnesses for players and spectators, ranging from heat exhaustion to potentially life-threatening heat strokes (Bergeron et al., 2011). Reports indicate that the elevated surface temperatures of Astroturf fields contribute to a heightened risk of heat-related illnesses, resulting in incidents ranging from heat cramps to heat exhaustion and heat strokes (Bergeron et al., 2011). Additionally, studies have suggested a higher incidence of ankle and foot injuries on astroturf than on natural turf. It is worth noting that conflicting reports exist, and some studies indicating lower injury rates on astroturf have faced scrutiny due to their association with the Astroturf industry (Kanaan et al., 2020).

In terms of respiratory diseases, the synthetic materials used in astroturf, especially under high temperatures, can release harmful chemicals, including polycyclic aromatic hydrocarbons (PAHs), phthalates, and per- and poly-fluoroalkyl substances (PFAS). These materials are known carcinogens, neurotoxicants, mutagens, and endocrine disruptors (Murphy & Warner, 2022). Astroturf also significantly affects the ecotoxicity of freshwater far more throughout its use and maintenance than natural turf maintenance (Russo et al., 2022).

When dealing with land heating issues, as in the case of astroturf, conducting large-scale research and monitoring across broad areas is often necessary. One standard method used for this purpose is satellite imagery, which provides comprehensive data on Land Surface Temperatures (LST) across a vast expanse. However, utilizing this data for LST analysis poses data consistency and computational demands challenges. To overcome these challenges, Google Earth Engine (GEE) has emerged as a valuable platform, utilizing Google’s computational resources for remote sensing data analysis. GEE allows users to analyze data directly within the platform, eliminating the need for local data storage (Avdan & Jovanovska, 2016; Ermida et al., 2020).

To conduct this kind of research, Landsat 8’s Band 10, which is dedicated to thermal infrared sensing, can be used as a key component in LST estimation algorithms, providing valuable insights into thermal conditions and values in the imagery. As demonstrated in research, such algorithms exhibit potential in estimating LST with reasonable accuracy compared to near-surface air temperature measurements. However, it is essential to recognize that LST and near-surface air temperature can differ due to variations in measurement height. Moreover, Landsat 8’s spatial resolution, while suitable for many applications, has limitations for capturing fine-scale temperature variations. Nevertheless, Landsat 8 has been proven to be an available and accurate tool for achieving Land Surface Temperatures and extracting values on an extensive range of land efficiently (Avdan & Jovanovska, 2016; Ermida et al., 2020).

In conclusion, this literature review examines the complex relationship between astroturf, temperature, health, and climate. Astroturf, often used as a substitute for natural grass in sports facilities and gardens, poses several environmental and health risks. The astroturf can become much hotter than natural grass, which requires more water to cool down. The heating of astroturf can lead to the release of harmful chemicals, posing potential health risks. Additionally, prolonged exposure to elevated temperatures on astroturf can lead to heat-related illnesses and increase the risk of injuries. These factors highlight the importance of understanding the complex effects of astroturf. The use of remote sensing platforms, such as Google Earth Engine and Landsat 8 imagery, has been found to be a viable approach to monitoring and researching land surface temperatures and assessing the heat impact of astroturf.